config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    resources :orders, only: [:index,:show,:create]
  end
  get 'sell', to: 'products#new'
  resources :category, only: :index
  resources :product_shipping_methods, only: :index
  resources :brands, only: :index
  resources :mypages, only: :index
  resources :profiles, only: [:index, :update]
  resources :cards, only: [:index,:new] do
    collection do
      post 'pay', to: 'cards#pay'
      delete 'delete', to: 'cards#delete'
    end
  end
  resources :signup_sns, only: :index
  devise_for :users, controllers:{
   registrations: 'users',
   omniauth_callbacks: "users/omniauth_callbacks"
   }
  resources :logouts, only: :index
  resources :searches
  resources :comments, only: :create
  resources :categories, only: [:index,:show]
  resources :user_infos, only: [:index,:update]
  resources :users, only: :show
end

app/models/search.rb
class Search < ApplicationRecord

  def self.search(keyword)
    redirect_to root_path if params[:keyword] == ""
    splitKeyword = params[:keyword].split(/[[:blank:]]+/)

    @products = []
    splitKeyword.each do |keyword|
      next if keyword == ""
      @products = Product.where('name Like(?)', "%#{params[:keyword]}%")
    end
    @products.uniq!
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search

  def index
    @categories = Category.all
    @size = ProductSize.all
    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")

    @products = @products.page(params[:page]).per(48)
    respond_to do |format|
      format.html
      format.json { render json: @brands}
    end
  end

  def set_search
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

end

app/views/searches/_header.html.haml
%header.header--sp
  .header--sp__inner
    %h1.header--sp__logo
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3403318254", alt: "mercari"
    .header--sp__user-nav
      = link_to "#", class: 'header--sp__user-icon' do
        %figure
          %i.fa-bell
      = link_to "#", class: 'header--sp__user-icon' do
        %figure
          %i.fa-check
      = link_to "#", class: 'header--sp__user-icon header--sp__user-profile' do
        %figure
          %div
            = image_tag "//static.mercdn.net/thumb/members/164317197.jpg?1419725926", width: "32", alt: ""
  .header--sp__search-bar
    %form.header--sp__form{action: "#"}
      %input.header--sp__search{name: "keyword", placeholder: "何をお探しですか？", type: "search",value: ""}/
      %i.fa-search
  %nav.header--sp__nav
    = link_to "#", data: {category: "NAVIGATION", label: "sp_header_nav_カテゴリから探す"} do
      %i.fa-list-ul.header--sp__cat-brand-icon
      %span カテゴリから探す
    = link_to "#", data: {category: "NAVIGATION", label: "sp_header_nav_ブランドから探す"} do
      %i.fa-tag.header--sp__cat-brand-icon
      %span ブランドから探す
%header.header--pc
  .header--pc__inner
    %h1
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3403318254", height: "36",width: "134", alt: "mercari"
    = form_tag searches_path, method: :get,class: "header--pc__form" do
      %input.header--pc__search{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}
      = button_tag type: 'submit', class: 'header--pc__form--btn' do
        %i.fa-search
    .header--pc__nav--box
      %nav.header--pc__nav--box__nav
        %ul.header--pc__nav
          %li
            %h2
              = link_to "#", class: 'header--pc__nav--root list-parent' do
                %i.fa.fa-list-ul.header--pc__cat-brand-icon
                %span カテゴリーから探す
            %ul.header--pc__nav--parent-wrap{"data-mega": "1"}
              %li.header--pc__nav--parent
                %h3
                  = link_to "レディース", "https://www.mercari.com/jp/category/1/"
                %ul.header--pc__nav--child-wrap{"data-mega": "2"}
                  %li.header--pc__nav--child
                    = link_to "トップス", "https://www.mercari.com/jp/category/11/"
                    %ul.header--pc__nav--grand-child-wrap{"data-mega": "3"}
                      %li.header--pc__nav--grand-child
                        = link_to "Tシャツ/カットソー(半袖/袖なし)", "https://www.mercari.com/jp/category/119/"
              %li.header--pc__nav--nochild
                %h3
                  = link_to "カテゴリー一覧", "https://www.mercari.com/jp/category/"
          %li
            %h2
              = link_to "https://www.mercari.com/jp/brand/", class: 'header--pc__nav--root list-parent' do
                %i.fa.fa-tag.header--pc__cat-brand-icon
                %span ブランドから探す
              %ul.header--pc__nav--parent-wrap
                %li.header--pc__nav--parent
                  %h3
                    = link_to "シャネル","https://www.mercari.com/jp/brand/658/"
                %li.header--pc__nav--parent
                  %h3
                    = link_to "ブランド一覧","https://www.mercari.com/jp/brand/"
      .header--pc__user-wrapper
        %ul.header--pc__user-nav
          %li{"data-id": "header--pc__user-nav", "data-key": "notification_list", "data-url": "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}
            = link_to "https://www.mercari.com/jp/mypage/notification/", data: {url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"} ,class: "header--pc__nav--root" do
              %i.fa-bell
              %span お知らせ
            %ul.header--pc__user-box.header--pc__notification-box.mypage__item-list{"data-id": "header--pc__user-items"}
          %li{"data-id": "header--pc__user-nav", "data-key": "todo_list", "data-url": "https://www.mercari.com/jp/mypage/notification_and_todo_json/"}
            = link_to "https://www.mercari.com/jp/mypage/todo/", data: {url: "https://www.mercari.com/jp/mypage/notification_and_todo_json/"} ,class: "header--pc__nav--root" do
              %i.fa-check
              %span やることリスト
            %ul.header--pc__user-box.header--pc__todo-box.mypage__item-list{"data-id": "header--pc__user-items"}
          %li
            = link_to "https://www.mercari.com/jp/mypage/", class: 'header--pc__user-icon header--pc__nav--root' do
              %figure
                %div
                  = image_tag "/images/member_no_image.png", width: "32", alt: ""
              %div マイページ
            .header--pc__user-box.header--pc__mypage--box
              .header--pc__mypage--state
                %figure
                  %div
                    = image_tag "/images/member_no_image.png", width: "60", alt: ""
                  %figcaption unKnown User
                %ul.header--pc__mypage__review-listing
                  %li
                    = link_to "評価: 0","https://www.mercari.com/jp/mypage/review/history/"
                  %li
                    = link_to "出品数: 0","https://www.mercari.com/jp/mypage/listings/listing/"
                %ul.header--pc__mypage__sales-point
                  %li
                    = link_to "https://www.mercari.com/jp/mypage/sales/" do
                      .l-left
                        売上金
                      .l-right
                        ¥ 0
                        %i.fa-angle-right
                  %li
                    = link_to "https://www.mercari.com/jp/mypage/point/" do
                      .l-left ポイント
                      .l-right
                        P 0
                        %i.fa-angle-right
              %ul.mypage__nav--list
                %li
                  = link_to "https://www.mercari.com/jp/mypage/like/history/", class: 'mypage__nav--list-item' do
                    いいね！一覧
                    %i.fa-angle-right
                %li
                  = link_to "https://www.mercari.com/jp/mypage/listings/listing/", class: 'mypage__nav--list-item' do
                    出品した商品 - 出品中
                    %i.fa-angle-right
                %li
                  = link_to "https://www.mercari.com/jp/mypage/listings/in_progress/", class: 'mypage__nav--list-item' do
                    出品した商品 - 取引中
                    %i.fa-angle-right
                %li
                  = link_to "https://www.mercari.com/jp/mypage/listings/completed/", class: 'mypage__nav--list-item' do
                    出品した商品 - 売却済み
                    %i.fa-angle-right
                %li
                  = link_to "https://www.mercari.com/jp/mypage/purchase/", class: 'mypage__nav--list-item' do
                    購入した商品 - 取引中
                    %i.fa-angle-right
                %li
                  = link_to "https://www.mercari.com/jp/mypage/purchased/", class: 'mypage__nav--list-item' do
                    購入した商品 - 過去の取引
                    %i.fa-angle-right

app/views/searches/index.html.haml
.search__container
  .search__container__item
    %h2.search__container__item--h2
      %p.search__container__item--h2--p
        - if @products.present?
          検索結果 #{(@products.offset_value)+1}-#{@products.offset_value+@products.length}件
        - else
          検索結果 0 件
          %h2 該当する商品が見つかりません。商品は毎日増えていますので、メルカリ先生のこれからの作品に期待してください。
    .search__container__item__r-box
      = render @products
    .search__container__item__pagenator
      = paginate @products unless @products.nil?
  .search__container__side
    = form_tag('/searches', method: 'get',class:"search__container__side__form")  do
      .search__container__side__form__switch
        .search__container__side__form__switch--wrap
          = select '',:sort,{},{},class: 'select-default sort-select' do
            %option{value: 0}並び替え
            %option{value: 1} 価格の安い順
            %option{value: 2} 価格の高い順
            %option{value: 3} 出品の古い順
            %option{value: 4} 出品の新しい順
            %option{value: 5} いいね！の多い順
          %i.fas.fa-chevron-down
        = submit_tag "",class:'btn-other'
    .search__container__side__form__dropdown
      = search_form_for @q, url:searches_path do |f|
        %h3.search__container__side__form__dropdown--h3
          詳細検索
        .search__container__side__form__dropdown__wrap
          = f.label "", class: "label--default" do
            %i.fas.fa-plus
            %span キーワードを追加する
          = f.text_field :name_or_description_cont, placeholder: '例)値下げ交渉お断り' , class: "input--default"
        .search__container__side__form__dropdown__wraps
          = f.label "" do
            %i.fa.fa-list-ul
            %span カテゴリーを選択する
          .search__container__side__form__dropdown__wraps--select
            = f.select :category_main_category_id_eq,{},{},class: "select--default area1" do
              %option{value: "",selected: "true"} すべて
              - @categories.each do |ele|
                - next if ele.sub_subcategory_id.present?
                - next if ele.sub_category_id.present?
                %option{value: "#{ele.id}"}#{ele.name}
            %i.fas.fa-chevron-down
          .search__container__side__form__dropdown__wraps--select.area2div
            = f.select :category_sub_category_id_eq,{},{},class: "select--default area2",disabled: "true" do
              %option{value: "",selected: "true"}すべて
              - @categories.each do |ele|
                - next if ele.sub_subcategory_id.present?
                - next if ele.sub_category_id.nil?
                %option{value: "#{ele.sub_category_id}",'data-group': "#{ele.main_category_id}",'subdata-group': "#{ele.sub_category_id}"}#{ele.name}
            %i.fas.fa-chevron-down
          .search__container__side__form__dropdown__wraps--select.area3div
            .checkbox-default.area3.check_box1
              .checkbox-default.area3.check_box{disabled: "true"}
              - @categories.each do |ele|
                - next if ele.sub_category_id.nil?
                - next if ele.sub_subcategory_id.nil?
                .checkbox-default.area3.check_box.check_box1{'data-group': "#{ele.main_category_id}",'subdata-group': "#{ele.sub_category_id}"}
                  = f.check_box :category_sub_subcategory_id_eq_all_any,{id: "#{ele.name}", class: "check_box check_box1", 'data-group': "#{ele.main_category_id}",'subdata-group': "#{ele.sub_category_id}",checked: false},ele.sub_subcategory_id,nil
                  = f.label "#{ele.name}", for: "#{ele.name}", class: "check_box check_box1", 'data-group': "#{ele.main_category_id}",'subdata-group': "#{ele.sub_category_id}"
        .search__container__side__form__dropdown__wrap
          = f.label "" ,class: "label--default" do
            %i.fa.fa-tag
            %span ブランド名から探す
          %input{type: 'text_field', placeholder: '例)シャネル' , class: "input--default brand--input", value: ""}
          %ul.brand--ul{'data-search': "brand-dom"}
          = f.text_field :brand_id_eq ,class: 'hidden-brand--input'
        .search__container__side__form__dropdown__wraps
          = f.label "",class: "label--default" do
            %i.fas.fa-text-height
            %span サイズを指定する
          = f.select :product_size_id_eq,{},{},class: "select--default size_area1" do
            %option{value: "",selected: "true"}すべて
            - @size.each do |ele|
              - next if ele.product_size_id.present?
              %option{value: "#{ele.id}",size: "#{ele.id}"}#{ele.name}
          %i.fas.fa-chevron-down#fa-chevron-down
          .checkbox-show.size_area2div
            .checkbox-default.size_area2.check_box2{disabled: "true"}
            - @size.each do |ele|
              - next if ele.product_size_id.nil?
              .checkbox-default.size_area2.check_box.check_box2{'data-group': "#{ele.product_size_id}"}
                = f.check_box :product_size_id_eq_any,{id: "#{ele.name}", class: "check_box check_box2", 'data-group': "#{ele.product_size_id}",checked: false},ele.id,nil
                = f.label "#{ele.name}", for: "#{ele.name}", class: "check_box check_box2", 'data-group': "#{ele.product_size_id}"
        .search__container__side__form__dropdown__price
          = f.label "",class: "label--default" do
            %i.fas.fa-dollar-sign
            %span 価格
          %select.select--default.price-select
            %option 選択してください
            %option{id:"300-"}300 ~ 1000
            %option{id: "1000-"}1000 ~ 5000
            %option{id: "5000-"}5000 ~ 10000
            %option{id: "10000-"}10000 ~ 30000
            %option{id: "30000-"}30000 ~ 50000
            %option{id: "50000-"}50000 ~
          %i.fas.fa-chevron-down
          = f.number_field :price_gteq, placeholder: '¥ Min' , class: "input--default min"
          %span ~
          = f.number_field :price_lteq, placeholder: '¥ Max' , class: "input--default max"
        .search__container__side__form__dropdown__status
          = f.label "",class: "label--default"  do
            %i.fa.fa-star
            %span 商品の状態
          .search__container__side__form__dropdown__status--checkbox
            %label
              %input{type: 'checkbox',class: "all_check_1" } すべて
            =f.collection_check_boxes(:status_id_eq_any, Status.all, :id, :name) do |b|
              = b.label class: "check_1" do
                = b.check_box + b.text
        .search__container__side__form__dropdown__ship
          = f.label "",class: "label--default" do
            %i.fas.fa-truck
            %span 配送料の負担
          .search__container__side__form__dropdown__ship--checkbox
            %label
              %input{type: 'checkbox',class: "all_check_2"} すべて
            =f.collection_check_boxes(:shipping_fee_id_eq_any, ShippingFee.all, :id, :name) do |b|
              = b.label class: "check_2" do
                = b.check_box + b.text
        .search__container__side__form__dropdown__sold
          = f.label "",class: "label--default" do
            %i.fas.fa-shopping-cart
            %span 販売状況
          .search__container__side__form__dropdown__sold--checkbox
            %label
              %input{type: 'checkbox',class: "all_check_3"} すべて
            =f.collection_check_boxes(:sold_eq_any, Sold.all, :id, :name) do |b|
              = b.label class: "check_3" do
                = b.check_box + b.text
        .search__container__side__form__dropdown__sortlinkc
          = sort_link @q, :price, [:price, 'price asc'],{},id: 'sort_1'
          = sort_link @q, :price, [:price, 'price desc'],{},id: 'sort_2'
          = sort_link @q, :crea3ed_at, [:created_at, 'created_at desc'],{},id: 'sort_3'
          = sort_link @q, :created_at, [:created_at, 'created_at asc'],{},id: 'sort_4'
          = sort_link @q, :like, [:like_product_id_count, 'like_product_id_count desc'],{},id: 'sort_5'
        .search__container__side__form__dropdown__btn
          %input{ value: "クリア", type: 'reset',class: 'btn--default btn-gray'}
          = f.submit "完了", type: "submit", class: "btn--default btn-red"