config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    resources :orders, only: [:index,:show,:create]
  end
  get 'sell', to: 'products#new'
  resources :category, only: :index
  resources :product_shipping_methods, only: :index
  resources :brands, only: :index
  resources :mypages, only: :index
  resources :profiles, only: [:index, :update]
  resources :cards, only: [:index,:new] do
    collection do
      post 'pay', to: 'cards#pay'
      delete 'delete', to: 'cards#delete'
    end
  end
  resources :signup_sns, only: :index
  devise_for :users, controllers:{
   registrations: 'users',
   omniauth_callbacks: "users/omniauth_callbacks"
   }
  resources :logouts, only: :index
  resources :searches
  resources :comments, only: :create
  resources :categories, only: [:index,:show]
  resources :user_infos, only: [:index,:update]
  resources :users, only: :show
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    require "payjp"
    before_action :authenticate_user!
    before_action :set_request_from,only: :index

    def index
        @card = Card.where(user_id: current_user.id).first
        unless @card.blank?
            Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
            customer = Payjp::Customer.retrieve(@card.customer_id)
            @card_infomation = customer.cards.retrieve(@card.card_id)
        end
    end

    def new
    end

    def pay
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.create(card: params[:payjpToken])
        @card = Card.new(user_id: current_user.id,
                            customer_id: customer.id,
                            card_id: customer.default_card)
        if @card.save
            redirect_to session.delete(:return_to), notice: "カード情報の登録に成功しました"
        else
            redirect_to pay_cards_path
        end
    end

    def delete
        @card = Card.where(user_id: current_user.id).first
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(@card.customer_id)
        customer.delete
        @card.delete
        redirect_to cards_path
    end

    def set_request_from
        request.referer.include?('user_infos') ? session[:return_to] = mypages_path : session[:return_to] = request.referer
    end

end

app/views/cards/_active_tab.html.haml
%li.profile__container__navi--list--item.active
    .profile__container__navi--list--item--a
        = link_to "#{url}" do
            #{contents}
            %i.fas.fa-chevron-right

app/views/cards/_add.html.haml
%section.card__container__top__section__info__add
    .card__container__top__section__info__add--btn.navi--hover
        = link_to '/cards/new',class: 'btn-default' do
            %i.fas.fa-credit-card
            %p クレジットカードを追加する

app/views/cards/_cards.html.haml
%li.card__container__top__section__info__title--list--card__list
    %form.card__container__top__section__info__title--list--card__list__form
        %figure.card__container__top__section__info__title--list--card__list__form--figure
            - if @card_infomation.brand == 'Visa'
                = image_tag '/images/visa.svg', id: "visa"
            - elsif @card_infomation.brand == 'MasterCard'
                = image_tag '/images/master-card.svg', id: 'master'
            -elsif @card_infomation.brand == 'JCB'
                = image_tag '/images/jcb.svg"', id: 'jcb'
        .card__container__top__section__info__title--list--card__list__form--num #{"**** **** **** " + @card_infomation.last4}
        .card__container__top__section__info__title--list--card__list__form--num #{@card_infomation.exp_month.to_s+"/"+@card_infomation.exp_year.to_s.slice(2,3)}
        = link_to delete_cards_path,method: :delete do
            %button.card__container__top__section__info__title--list--card__list__form--remove{type: "submit"} 削除する

app/views/cards/index.html.haml
.card__container
    .card__container__top
        %section.card__container__top__section
            %h2 支払い方法
            .card__container__top__section__info
                %section.card__container__top__section__info__title
                    .card__container__top__section__info__title--list
                        %h3 クレジットカード一覧
                    %ul.card__container__top__section__info__title--list--card
                        - if @card.present?
                            = render partial: "cards"
                - if @card.nil?
                    = render partial: "add"
                .card__container__top__section__info__not
                    %p.card__container__top__info__not--p
                        = link_to "支払い方法について", '#'
                        %i.fas.fa-chevron-right

    .card__container__navi
        %ul.card__container__navi--list
            -# renderで部分テンプレート 条件分岐未実装
            = render partial: "top_tab", locals: { url:'#', contents: 'マイページ' }
            = render partial: "tab", locals: { url:'#', contents: 'おしらせ'  }
            = render partial: "tab", locals: { url:'#', contents: 'やることリスト'  }
            = render partial: "tab", locals: { url:'#', contents: 'いいね！一覧'  }
            = render partial: "tab", locals: { url:'#', contents: '出品する'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 出品中'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 取引中'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 売却済み'  }
            = render partial: "tab", locals: { url:'#', contents: '購入した商品 - 取引中'  }
            = render partial: "tab", locals: { url:'#', contents: '購入した商品 - 過去の取引'  }
            = render partial: "tab", locals: { url:'#', contents: 'ニュース 一覧'  }
            = render partial: "tab", locals: { url:'#', contents: '評価一覧'  }
            = render partial: "tab", locals: { url:'#', contents: 'ガイド'  }
            = render partial: "tab", locals: { url:'#', contents: 'お問い合わせ'  }
            %h3 メルペイ
            -# .toplistで上部border-lineを消去
            = render partial: "top_tab", locals: { url:'#', contents: '売上・振込申請' }
            = render partial: "tab", locals: { url:'#', contents: 'ポイント' }
            %h3 設定
            = render partial: "top_tab", locals: { url:profiles_path, contents: 'プロフィール' }
            = render partial: "tab", locals: { url:'#', contents: '発送元・お届け先住所変更' }
            = render partial: "active_tab", locals: { url:'#', contents: '支払い方法' }
            = render partial: "tab", locals: { url:'#', contents: 'メール / パスワード'  }
            = render partial: "tab", locals: { url:'#', contents: '本人情報' }
            = render partial: "tab", locals: { url:'#', contents: '電話番号の確認' }
            = render partial: "tab", locals: { url:'#', contents: 'ログアウト' }

app/views/cards/new.html.haml
.ccreate__container
    %section.ccreate__container__top
        %h2 クレジットカード情報入力
        = form_tag(pay_cards_path,method: :post, id:'charge-form',class:'ccreate__container__top__form') do
            .ccreate__container__top__form__content
                .ccreate__container__top__form__content--group
                    %label{for: "payment_card_no", class: "input--label"} カード番号
                    %span.require 必須
                    %input.input--default{type: "text", id: "card_number", placeholder: "半角数字のみ", 'data-input-type': "card", class: "input-default", pattern: "^[0-9]+$", maxlength: '16'}
                    %ul.ccreate__container__top__form__content--group--brand
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/visa.svg", id: "visa"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/master-card.svg", id: "master"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/saison-card.svg", id: "saison"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/jcb.svg", id: "jcb"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/american_express.svg", id: "express"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/dinersclub.svg", id: "diners"}
                        %li.ccreate__container__top__form__content--group--brand--list
                            %img{ src:"/images/discover.svg", id: "discover"}
                .ccreate__container__top__form__content--expire
                    %label{for: "payment_card_no", class: "input--label"} 有効期限
                    %span.require 必須
                    .ccreate__container__top__form__content--expire--wrap
                        %select{name:"exp_month", class: "select-default",id: 'exp_month'}
                            %option{value: "01"} 01
                            %option{value: "02"} 02
                            %option{value: "03"} 03
                            %option{value: "04"} 04
                            %option{value: "05"} 05
                            %option{value: "06"} 06
                            %option{value: "07"} 07
                            %option{value: "08"} 08
                            %option{value: "09"} 09
                            %option{value: "10"} 10
                            %option{value: "11"} 11
                            %option{value: "12"} 12
                        %i.fas.fa-chevron-down
                    %span.select-month 月
                    .ccreate__container__top__form__content--expire--wrap
                        %select{name:"exp_year", class: "select-default", id: 'exp_year'}
                            %option{value: "2019"}19
                            %option{value: "2020"}20
                            %option{value: "2021"}21
                            %option{value: "2022"}22
                            %option{value: "2023"}23
                            %option{value: "2024"}24
                            %option{value: "2025"}25
                            %option{value: "2026"}26
                            %option{value: "2027"}27
                            %option{value: "2028"}28
                            %option{value: "2029"}29
                        %i.fas.fa-chevron-down
                    %span.select-yeah 年
                .ccreate__container__top__form__content--code
                    %label{for: "payment_card_no", class: "input--label"} セキュリティコード
                    %span.require 必須
                    %input.input--default{name: 'cvc',type: "text", id: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", class: "input-default",
                    pattern: "^[0-9]+$", maxlength: '4'}
                .ccreate__container__top__form__content--sequ
                    .ccreate__container__top__form__content--sequ--text
                        %i.fas.fa-question-circle
                        %p.sequ_box カード裏面の番号とは？
                        .arrow_box
                            %p カードの裏面をご参照ください。
                %button{type: "submit", class: "btn-default",id: "submit-button",  href: "#"} 追加する
    .ccreate__container__navi
        %ul.ccreate__container__navi--list
            -# renderで部分テンプレート 条件分岐未実装
            = render partial: "top_tab", locals: { url:'#', contents: 'マイページ' }
            = render partial: "tab", locals: { url:'#', contents: 'おしらせ'  }
            = render partial: "tab", locals: { url:'#', contents: 'やることリスト'  }
            = render partial: "tab", locals: { url:'#', contents: 'いいね！一覧'  }
            = render partial: "tab", locals: { url:'#', contents: '出品する'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 出品中'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 取引中'  }
            = render partial: "tab", locals: { url:'#', contents: '出品した商品 - 売却済み'  }
            = render partial: "tab", locals: { url:'#', contents: '購入した商品 - 取引中'  }
            = render partial: "tab", locals: { url:'#', contents: '購入した商品 - 過去の取引'  }
            = render partial: "tab", locals: { url:'#', contents: 'ニュース 一覧'  }
            = render partial: "tab", locals: { url:'#', contents: '評価一覧'  }
            = render partial: "tab", locals: { url:'#', contents: 'ガイド'  }
            = render partial: "tab", locals: { url:'#', contents: 'お問い合わせ'  }
            %h3 メルペイ
            -# .toplistで上部border-lineを消去
            = render partial: "top_tab", locals: { url:'#', contents: '売上・振込申請' }
            = render partial: "tab", locals: { url:'#', contents: 'ポイント' }
            %h3 設定
            = render partial: "top_tab", locals: { url:profiles_path, contents: 'プロフィール' }
            = render partial: "tab", locals: { url:'#', contents: '発送元・お届け先住所変更' }
            = render partial: "active_tab", locals: { url:'#', contents: '支払い方法' }
            = render partial: "tab", locals: { url:'#', contents: 'メール / パスワード'  }
            = render partial: "tab", locals: { url:'#', contents: '本人情報' }
            = render partial: "tab", locals: { url:'#', contents: '電話番号の確認' }
            = render partial: "tab", locals: { url:'#', contents: 'ログアウト' }