config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    resources :orders, only: [:index,:show,:create]
  end
  get 'sell', to: 'products#new'
  resources :category, only: :index
  resources :product_shipping_methods, only: :index
  resources :brands, only: :index
  resources :mypages, only: :index
  resources :profiles, only: [:index, :update]
  resources :cards, only: [:index,:new] do
    collection do
      post 'pay', to: 'cards#pay'
      delete 'delete', to: 'cards#delete'
    end
  end
  resources :signup_sns, only: :index
  devise_for :users, controllers:{
   registrations: 'users',
   omniauth_callbacks: "users/omniauth_callbacks"
   }
  resources :logouts, only: :index
  resources :searches
  resources :comments, only: :create
  resources :categories, only: [:index,:show]
  resources :user_infos, only: [:index,:update]
  resources :users, only: :show
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :status_id, :shipping_fee_id, :state_id, :shipping_method_id, :shipping_day_id, :price, :description, :user_id
  validates :name, length: { maximum: 40 }
  validates :price, numericality: {greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, only_integer: true}
  validates :description, length: { maximum: 100 }

  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one :order

  def previous
    Product.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Product.where("id > ?", self.id).order("id ASC").first
  end


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :category
  belongs_to_active_hash :brand
  belongs_to_active_hash :status
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :state
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :now_product, only: %i[show search_rate category_define]
  before_action :authenticate_user!, only: [:new,:create,:destroy,:edit,:update]

    def index
        @products = Product.all.limit(48)
    end

    def new
        @product = Product.new
        @product.product_images.build
        @main_categories = Category.where(sub_category_id: nil)
        @new_product = Product.where(user_id: current_user.id).order(created_at: :desc).limit(1)
        respond_to do |format|
            format.html
            format.json {@new_product}
        end
        render layout: "sell"
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            create_productimage(@product.id)
            respond_to do |format|
                format.html { redirect_to root_path }
                format.json
            end
        else
            @product.product_images.build
            respond_to do |format|
                format.html{render new_product_path}
                format.json
            end
        end
    end

  def show
      @get_image = get_image
      @search_rate3 = search_rate(3)
      @search_rate2 = search_rate(2)
      @search_rate1 = search_rate(1)
      @category_defines = defined_category
      @likes = Like.where(product_id: @product.id)
      @comments = Comment.where(product_id: params[:id])
      @comment = Comment.new
      @exclusion_products = Product.where(user_id: @product.user_id).where.not(id: params[:id]).limit(6)
      @exclusion_product_brands = Product.where(brand_id: @product.brand_id).where.not(id: params[:id]).limit(6)
      user_signed_in? ? @user_id = current_user.id : @user_id = 0
end

    def destroy
        @product =  Product.find(params[:id])
        @product.destroy
        redirect_to root_path, notice: "削除しました"
    end

    def edit
        @product = Product.find(params[:id])
        @product_images = ProductImage.where(product_id: @product.id)
        @category_id = @product.category_id
        @main_categories = Category.where(sub_category_id: nil)
        @sub_categories = Category.sub_category_search(@product.category.main_category_id)
        @sub_subcategories = Category.where(main_category_id: @product.category.main_category_id,sub_category_id: @product.category.sub_category_id).where.not(sub_subcategory_id: nil)
        render layout: "sell"
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            update_productimage(@product)
            respond_to do |format|
                format.html { redirect_to product_path }
                format.json
            end
        else
            @category_id = @product.category_id
            @main_categories = Category.where(sub_category_id: nil)
            @sub_categories = Category.sub_category_search(@product.category.main_category_id)
            @sub_subcategories = Category.where(main_category_id: @product.category.main_category_id,sub_category_id: @product.category.sub_category_id).where.not(sub_subcategory_id: nil)    
            respond_to do |format|
                format.html{render edit_product_path}
                format.json
            end
        end
    end

    #product_imageの4個分配列作成
    def get_image
      @images = []
      @product.product_images.each do |product|
        @images <<  product.image_url
      end
    end

    # ユーザーの評価の配列を取り出す関数
    def search_rate(rate)
      @rate_id = @product.user.id
      @return = Rate.where(user_id: @rate_id, rate: rate)
    end

    # カテゴリーごとの名称取得関数（配列で出力）
    def defined_category
      @category_id = @product.category_id
      @main_id = @product.category.main_category_id
      @sub_id = @product.category.sub_category_id
      @subsub_id = @product.category.sub_subcategory_id
      if @subsub_id == nil
        main_name = Category.find(@main_id).name
        sub = Category.find_by(main_category_id: @main_id,sub_category_id: @sub_id, sub_subcategory_id: nil)
        subsub_name = nil
      elsif  @sub_id == nil
        main_name = Category.find(@main_id).name
        sub, subsub_name = nil
      else
        main_name = Category.find(@main_id).name
        sub = Category.find_by(main_category_id: @main_id,sub_category_id: @sub_id, sub_subcategory_id: nil)
        subsub_name = Category.find(@category_id).name
      end
      return main_name, sub.name, subsub_name,sub.id
    end

    private

    def now_product
      @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:name,:status_id,:shipping_fee_id,:state_id,:shipping_method_id,:shipping_day_id,:price,:product_size_id,:description,:category_id,:brand_id, product_images_attributes: [:image_url]).merge(user_id: current_user.id)
    end

    def create_productimage(product_id)
        i = 0
        while params[:product][:product_images_attributes][:image_url][i.to_s].present? do
            image = params[:product][:product_images_attributes][:image_url][i.to_s]
            ProductImage.create(product_id: product_id, image_url: image)
            i += 1
        end
    end

    
    def update_productimage(product)
        if params[:DeletedImageUrls].present?
            i = 0
            while params[:DeletedImageUrls][i].present? do
                product_image = product.product_images.find_by(image_url: params[:DeletedImageUrls])
                product_image.destroy if product_image.present?
                i += 1
            end
        end
        if params[:product][:product_images_attributes].present?
            i = 0
            while params[:product][:product_images_attributes][:image_url][i.to_s].present? do
                image = params[:product][:product_images_attributes][:image_url][i.to_s]
                ProductImage.create(product_id: product.id, image_url: image)
                i += 1
            end
        end
    end

end

app/helpers/products_helper.rb
module ProductsHelper

  def converting_to_jpy(price)
    price = "¥ " + price.to_s(:delimited)
  end

  def product_image(product)
    product.product_images.first.image_url.url
  end

end

app/views/products/_product.html.haml
%section.items-box
  = link_to product_path(product.id),data: {"turbolinks" => false} do
    %figure.items-box__photo
      = image_tag product_image(product), alt: product.name
    .items-box__bod
      %h3.items-box__name 
        = product.name
      .items-box__num
        .items-box__price 
          = converting_to_jpy(product.price)
        - if product.likes.count > 0
          .items-box__likes
            %i.fa-heart
            %span
              = product.likes.count
        %p.item-box__tax (税込)

app/views/products/index.html.haml
.main-container
  %section.top-banner__container
    = link_to "#", "https://mercari-special.jp/~natsukashi/", class: 'top-banner__banner-natsukashi'
  %section.pickup__container
    %h2.pickup__head 商品一覧
    %section.items-box__container
      %h3
        = link_to "", "category_index_path"
      .items-box__content
        = render @products

app/views/products/new.html.haml
%header.header--single
    .header--single__inner 
        %h1.header--single__logo
            = link_to root_path do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1414406813",   alt: "mercari"
.sell__container
    .sell__container__top
        %section.sell__container__top__section
            %h2 商品の情報を入力
        .sell__container__top__section--form    
            = form_for @product, html: {class: 'dropzone', id: 'item-dropzone'} do |f|
                .sell__container__top__section--form--uploader
                    %h3.sell__container__top__section--form--uploader--head 
                        出品画像
                        %span 必須  
                    %p 最大10枚までアップロードできます
                    = f.fields_for :product_images do |image|
                        .dropzone
                            #dz-previews
                            .dz-message.needsclick
                                %pre ドラッグアンドドロップ<br>またはクリックしてファイルをアップロード
                                %i.fa-camera
                    %ul.sell__container__top__section--form--uploader--items
                .sell__container__top__section--form--groups
                    .sell__container__top__section--form--group--input
                        .sell__container__top__section--form--group--head
                            = f.label :商品名
                            %span 必須
                        %div
                            = f.text_field :name, class: "input-text", placeholder: "商品名（必須 40文字まで)"
                    .sell__container__top__section--form--group--input
                        .sell__container__top__section--form--group--head
                            = f.label :商品の説明  
                            %span 必須
                        .sell__container__top__section--form--group--text
                            = f.text_area :description, class: "sell__container__top__section--form--group--textarea", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
                .sell__container__top__section--form--groups
                    .sell__container__top__section--form--group--sub-head
                        = f.label :商品の詳細
                    .sell__container__top__section--form--group--content
                        .sell__container__top__section--form--group
                            .sell__container__top__section--form--group--head
                                = f.label :カテゴリー
                                %span 必須
                            .sell__container__top__section--form--group--select
                                = f.collection_select :category_id, Category.where(sub_category_id: nil), :id, :name, {prompt: "---"}, {class: 'sell__container__top__section--form--group--select--box'}
                                %i.fa-chevron-down
                        .sell__container__top__section--form--group
                            .sell__container__top__section--form--group--head
                                = f.label :商品の状態
                                %span 必須
                            .sell__container__top__section--form--group--select
                                = f.collection_select :status_id, ProductStatus.all, :id, :name, {prompt: "---"}, {class: 'sell__container__top__section--form--group--select--box'}
                                %i.fa-chevron-down
                .sell__container__top__section--form--groups
                    .sell__container__top__section--form--group--sub-head
                        = f.label :配送について
                        = link_to "?", "https://www.mercari.com/jp/help_center/article/68/",target: "_blank", class: 'sell__container__top__section--form--group--form-question'
                    .sell__container__top__section--form--group--content
                        .sell__container__top__section--form--group
                            .sell__container__top__section--form--group--head
                                = f.label :配送料の負担
                                %span 必須
                            .sell__container__top__section--form--group--select
                                = f.collection_select :shipping_fee_id, ProductShippingFee.all, :id, :name, {prompt: "---"}, {class: 'sell__container__top__section--form--group--select--box'}
                                %i.fa-chevron-down
                        .sell__container__top__section--form--group
                            .sell__container__top__section--form--group--head
                                = f.label :発送元の地域
                                %span 必須
                            .sell__container__top__section--form--group--select
                                = f.collection_select :state_id, Prefecture.all, :id, :name, {prompt: "---"}, {class: 'sell__container__top__section--form--group--select--box'}
                                %i.fa-chevron-down
                        .sell__container__top__section--form--group
                            .sell__container__top__section--form--group--head
                                = f.label :発送までの日数
                                %span 必須
                            .sell__container__top__section--form--group--select
                                = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, {prompt: "---"}, {class: 'sell__container__top__section--form--group--select--box'}
                                %i.fa-chevron-down
                .sell__container__top__section--form--groups
                    .sell__container__top__section--form--group--sub-head
                        .sell__container__top__section--form--group--input
                            = f.label :"販売価格(300〜9,999,999)"
                            = link_to "?", "https://www.mercari.com/jp/help_center/article/64/",target: "_blank", class: 'sell__container__top__section--form--group--form-question'
                    .sell__container__top__section--form--group--content
                        .sell__container__top__section--form--group--content--price
                            %ul.sell__container__top__section--form--group--content--price--group
                                %li.sell__container__top__section--form--group--content--price--group--input-top
                                    .sell__container__top__section--form--group--head
                                        = f.label :価格 
                                        %span 必須
                                    .sell__container__top__section--form--group--text#item_price
                                        ¥
                                        = f.text_field :price, class: "input-text #item_price", placeholder: "例）300"
                                %li.sell__container__top__section--form--group--content--price--group--input-middle
                                    .sell__container__top__section--form--group--content--price--group--input-middle--head
                                        = f.label :"販売手数料 (10%)"
                                    .sell__container__top__section--form--group--content--price--group--input-middle--text#commission
                                        = f.label :- 
                                %li.sell__container__top__section--form--group--content--price--group--input-last
                                    .sell__container__top__section--form--group--head
                                        = f.label :販売利益
                                    .sell__container__top__section--form--group--text#benefit
                                        = f.label :- 
                .sell__container__top__section--form--groups                       
                    .sell__container__top__section--form--bottom
                        .sell__container__top__section--form--bottom--p
                            .sell__container__top__section--form--content--price
                                %p
                                    = link_to "禁止されている出品", "https://www.mercari.com/j/jp/help_center/getting_started/prohibited_items/",target: "_blank"
                                    、
                                    = link_to "行為", "https://www.mercari.com/j/jp/help_center/getting_started/prohibited_conduct/",target: "_blank"
                                    を必ずご確認ください。
                                %p
                                    またブランド品でシリアルナンバー等がある場合はご記載ください。
                                    = link_to "偽ブランドの販売", "https://www.mercari.com/j/jp/help_center/getting_started/counterfeit_goods/",target: "_blank"
                                    は犯罪であり処罰される可能性があります。
                                %p
                                    また、出品をもちまして
                                    = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/",target: "_blank"
                                    に同意したことになります。
                            .sell__container__top__section--form--groupb
                                %button.btn--red{type: "submit"} 出品する
                                %button.btn--gray もどる
%footer.single-footer
    %nav
        %ul
        %li
            = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
        %li
            = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
        %li
            = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
    = link_to "https://www.mercari.com/jp/", class: 'single-footer-logo' do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?570108281", alt: "mercari", height: "65", width: "80"
    %p
        %small © 2019 Mercari
#overlay
#modalWindow
    .product-modal__container
        .product-modal__container__head
            %h1 出品が完了しました
        .product-modal__container__content
            %p あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。  
            =link_to sell_path, data: {"turbolinks" => false}, class: " product-modal__container__content__btn--red" do
                .product-modal__container__content__btn--red
                    %h1 続けて出品する

app/views/products/show.html.haml
- breadcrumb :product, @product
.items__container
  .items__container--h1 #{@product.name}
  .items__container__main
    .items__container__main__wrap#wrap
      %ul#slider
        - @product.product_images.each do |n|
          %li.slide-item
            = image_tag '','data-lazy': "#{n.image_url.url}", alt:''
      %ul#thumbnail-list
        - @product.product_images.each do |n|
          %li.thumbnail-item
            = image_tag "#{n.image_url.url}"
    .items__container__main__detail
      %table
        %tbody
          %tr
            %th 出品者
            %td
              =link_to "#{@product.user.nickname}", user_path(@product.user),class:'font-blue'
              .item-user
                .item-user-ratings
                  %i.fas.fa-grin
                  %span #{@search_rate3.count}
                .item-user-ratings
                  %i.fas.fa-meh
                  %span #{@search_rate2.count}
                .item-user-ratings
                  %i.fas.fa-frown
                  %span #{@search_rate1.count}
          %tr
            %th カテゴリー
            %td
              = link_to category_path(@main_id) do
                #item_main_category.font-blue
                  %p #{@category_defines[0]}
              - unless @category_defines[1].nil?
                = link_to category_path(@category_defines[3].to_i) do
                  #item_sub_category.font-blue
                    %i.fas.fa-chevron-right
                    %p.category-p #{@category_defines[1]}
              - unless @category_defines[2].nil?
                = link_to category_path(@category_id) do
                  #item_sub_subcategory.font-blue
                    %i.fas.fa-chevron-right
                    %p.category-p #{@category_defines[2]}
          %tr
            %th ブランド
            %td
              - if @product.brand.presence
                = link_to "#{@product.brand.name}","#",class:"font-blue"
          %tr
            %th 商品の状態
            %td #{@product.status.name}
          %tr
            %th 配送料の負担
            %td #{@product.shipping_fee.name}
          %tr
            %th 発送の方法
            %td #{@product.shipping_method.name}
          %tr
            %th 発送元地域
            %td
              = link_to "#{@product.state.name}","#",class:"font-blue"
          %tr
            %th 発送日の目安
            %td #{@product.shipping_day.name}
  .items__container__main__price
    %span.span-price
      = converting_to_jpy(@product.price)
    %span.span-tax (税込)
    %span.span-fee 送料込み
  - unless @product.user_id == @user_id
    .items__container__main__sold
      -if @product.sold == true
        .items__container__main__sold--true
          %h1 売り切れました
      - else
        = link_to product_orders_path(params[:id]),data: {"turbolinks" => false},class:"items__container__main__sold--a" do
          .items__container__main__sold--a--false
            %h1 購入画面に進む
  .items__container__main__description
    %p #{@product.description}
  .items__container__main__like
    .items__container__main__like__left
      = button_tag '',class: 'item-button item-button-like' do
        %i.far.fa-heart
        %p いいね!
        %p #{@likes.count}
      = link_to '',class: 'item-button-bad' do
        %i.far.fa-flag
        %p 不適切な商品の報告
    .items__container__main__like__right
      = link_to '', class: 'items__container__main__like__right--safe' do
        %i.fas.fa-lock
        %span あんしん・あんぜんへの取り組み
- if user_signed_in?
  - if @product.user_id == current_user.id
    .product-change__container
      .product-change__container__content
        =link_to edit_product_path, class: "      product-change__container__content__btn--red",data: {"turbolinks" => false} do
          .product-change__container__content__btn--red
            %h1 商品の編集
        %p or
        =link_to "/products/#{@product.id}", class: "      product-change__container__content__btn--gray", method: :delete, data:{confirm:'本当に削除しますか？'} do
          .product-change__container__content__btn--gray
            %h1 この商品を削除する
.message__container
  .message__container__content
    %ul.message__container__content--ul
      - @comments.each do |ele|
        %li.message__container__content--ul--li
          = link_to '#',class: "message__container__content--ul--li--user" do
            %figure.user_icon
              .user_icon
                -if ele.user.user_image.nil?
                  = image_tag "/images/member_no_image.png"
                - else
                  = image_tag "/images/#{ele.user.user_image[:image_url]}"
            - if ele.comment_deleted == false
              %p #{ele.user.nickname}
            - if ele.user_id == @product.user_id
              .div_seller
                %p 出品者
          .message__container__content--ul--li--body
            .message__container__content--ul--li--body--text
              - if ele.comment_deleted == true
                %p 出品者がコメントを削除しました
              - else
                %p #{ele.comment}
            .message__container__content--ul--li--body--time
              .time-icon-left
                %i.far.fa-clock
                %span #{distance_of_time_in_words_to_now(ele.created_at)}前
              - if ele.comment_deleted == false
                .time-icon-right
                  = link_to '#' do
                    %i.far.fa-flag
  - if user_signed_in? == true
    .message__container__comment
      = form_for(@comment, url: {controller: :comments, action: :create}, class: 'message__container__comment__form') do |f|
        %p.message__container__comment__form--p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        - if @product.sold == true
          = f.text_area :comment,{class: 'message__container__comment__form--input',disabled: 'disabled'}
          = f.submit '売り切れの為コメントできません',type: 'submit',class: 'message__container__comment__form--btn',disabled: 'disabled'
        - else
          = f.hidden_field :product_id, value: @product.id
          = f.text_area :comment,{class: 'message__container__comment__form--input'}
          = f.submit 'コメントする',type: 'submit',class: 'message__container__comment__form--btn'
        - if flash[:error].present?
          .error_explanation
            %ul.error_explanation--ul
              - flash[:error].each do |e|
                %li
                  = e
.item__nav
  %ul.item__nav__ul
    %li.item__nav__ul__prev
      - unless @product.previous == nil
        = link_to "#{@product.previous.id}",data: {"turbolinks" => false} do
          %i.fas.fa-chevron-left
          %p.item__nav__ul__prev--p #{@product.previous.name}
    %li.item__nav__ul__next
      - unless @product.next == nil
        = link_to "#{@product.next.id}",data: {"turbolinks" => false} do
          %p.item__nav__ul__next--p #{@product.next.name}
          %i.fas.fa-chevron-right
.item__sns
  %ul.item__sns--ul
    %li.item__sns--ul--facebook
      =link_to '#' do
        %i.fab.fa-facebook-square
    %li.item__sns--ul--twitter
      =link_to '#' do
        %i.fab.fa-twitter-square
    %li.item__sns--ul--pintrest
      =link_to '#' do
        %i.fab.fa-pinterest-square
.item__user-product
  %h2.item__user-product__user
    =link_to user_path(@product.user),class: 'item__user-product__user--a' do
      %h2 #{@product.user.nickname}さんのその他の出品
  .item__user-product__list
    - @exclusion_products.each do |product|
      = render partial: "products/product", locals: {product: product}
- unless @exclusion_product_brands.nil?
  .item__user-product
    - if @product.brand.presence
      %h2.item__user-product__user
        =link_to "",class: 'item__user-product__user--a' do
          %h2 #{@product.brand.name}の#{@category_defines[0]}その他の出品
      .item__user-product__list
        - @exclusion_product_brands.each do |product|
          = render partial: "products/product", locals: {product: product}